# Generated by Django 3.2.12 on 2022-05-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_genre_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='G',
        ),
    ]
