# Generated by Django 3.2.12 on 2022-05-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20220519_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Director', models.CharField(max_length=1000)),
                ('Actor', models.TextField()),
            ],
        ),
    ]
