# Generated by Django 3.2.12 on 2022-05-21 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_rename_trailer_trailers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailers',
            name='movie_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trailer', to='movies.movie'),
        ),
    ]
