# Generated by Django 3.2.12 on 2022-05-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20220523_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='like',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.FloatField(null=True),
        ),
    ]
