# Generated by Django 3.2.12 on 2022-05-23 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20220523_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
    ]
