# Generated by Django 3.2.12 on 2022-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0002_user_liked_movie_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_comment',
            field=models.ManyToManyField(related_name='user_liked', to='articles.Comment'),
        ),
    ]
