# Generated by Django 3.2.12 on 2022-05-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_remove_review_like'),
        ('accounts', '0004_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_Movie_review',
            field=models.ManyToManyField(related_name='user_review_liked', to='movies.Review'),
        ),
    ]
